extends Node

func _init():
	var overwrite_1 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Airport Lounge.mp3")
	overwrite_1.take_over_path("res://audio/music/DA_Office.ogg")
	var overwrite_2 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/All This.mp3")
	overwrite_2.take_over_path("res://audio/music/molten_mint/liquid_metal.ogg")
	var overwrite_3 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Basement Floor.mp3")
	overwrite_3.take_over_path("res://audio/music/encntr_general_bg_indoor.ogg")
	var overwrite_4 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Batty McFaddin - Slower.mp3")
	overwrite_4.take_over_path("res://audio/music/installer.ogg")
	var overwrite_5 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Move Forward.mp3")
	overwrite_5.take_over_path("res://audio/music/tc_streets.ogg")
	var overwrite_6 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Carpe Diem.mp3")
	overwrite_6.take_over_path("res://audio/music/encntr_hall_of_fame.ogg")
	var overwrite_7 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Chill.mp3")
	overwrite_7.take_over_path("res://audio/music/main_theme.ogg")
	var overwrite_8 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Cipher2.mp3")
	overwrite_8.take_over_path("res://audio/music/estate.ogg")
	var overwrite_9 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Cut and Run.mp3")
	overwrite_9.take_over_path("res://audio/music/CHQ_FACT_bg.ogg")
	var overwrite_10 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Darkest Child.mp3")
	overwrite_10.take_over_path("res://audio/music/Bossbot_Factory_v2.ogg")
	var overwrite_11 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Decisions.mp3")
	overwrite_11.take_over_path("res://audio/music/molten_mint/molten_mint.ogg")
	var overwrite_12 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Disco Lounge.mp3")
	overwrite_12.take_over_path("res://audio/music/action_law.ogg")
	var overwrite_13 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Enter the Party.mp3")
	overwrite_13.take_over_path("res://audio/music/encntr_general_bg_indoor.ogg")
	var overwrite_14 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Heartbreaking.mp3")
	overwrite_14.take_over_path("res://audio/music/Bossbot_Factory_v1.ogg")
	var overwrite_15 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Hitman.mp3")
	overwrite_15.take_over_path("res://audio/music/molten_mint/liquid_metal_proxy.ogg")
	var overwrite_16 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Iron Horse.mp3")
	overwrite_16.take_over_path("res://audio/music/action_cash.ogg")
	var overwrite_17 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Isolated.mp3")
	overwrite_17.take_over_path("res://audio/music/boss_lost.ogg")
	var overwrite_18 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Latin Industries.mp3")
	overwrite_18.take_over_path("res://audio/music/seize_the_means.ogg")
	var overwrite_19 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Local Forecast - Elevator.mp3")
	overwrite_19.take_over_path("res://audio/music/beta_installer.ogg")
	var overwrite_20 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Mariachi Snooze.mp3")
	overwrite_20.take_over_path("res://audio/music/MG_Pairing.ogg")
	var overwrite_21 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Mining by Moonlight.mp3")
	overwrite_21.take_over_path("res://audio/music/tt_elevator.ogg")
	var overwrite_22 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Movement Proposition.mp3")
	overwrite_22.take_over_path("res://audio/music/action_boss.ogg")
	var overwrite_23 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/MTA.mp3")
	overwrite_23.take_over_path("res://audio/music/action_sell.ogg")
	var overwrite_24 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Music to Delight.mp3")
	overwrite_24.take_over_path("res://audio/music/clown_boss.ogg")
	var overwrite_25 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Not As It Seems.mp3")
	overwrite_25.take_over_path("res://audio/music/Bossbot_Factory_v3.ogg")
	var overwrite_26 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Pixel Peeker Polka - faster.mp3")
	overwrite_26.take_over_path("res://audio/music/shopping.ogg")
	var overwrite_27 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Scheming Weasel slower.mp3")
	overwrite_27.take_over_path("res://audio/music/AShadeOfGiveOrTake.ogg")
	var overwrite_28 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Scissors.mp3")
	overwrite_28.take_over_path("res://audio/music/encntr_penultimate/pre_getw.ogg")
	var overwrite_29 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Shiny Tech.mp3")
	overwrite_29.take_over_path("res://audio/music/climb_boss.ogg")
	var overwrite_30 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Soporific.mp3")
	overwrite_30.take_over_path("res://audio/music/encntr_skull_master.ogg")
	var overwrite_31 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Spazzmatica Polka.mp3")
	overwrite_31.take_over_path("res://audio/music/radio_tune2.ogg")
	var overwrite_32 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/The Complex.mp3")
	overwrite_32.take_over_path("res://audio/music/BossBot_CEO_v1.ogg")
	var overwrite_33 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Unseen Horrors.mp3")
	overwrite_33.take_over_path("res://audio/music/Bossbot_Entry_v2.ogg")
	var overwrite_34 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Villainous Treachery.mp3")
	overwrite_34.take_over_path("res://audio/music/tax_return.ogg")
	var overwrite_35 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Volatile Reaction.mp3")
	overwrite_35.take_over_path("res://audio/music/molten_mint/liquidator_boss.ogg")
	var overwrite_36 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Wallpaper.mp3")
	overwrite_36.take_over_path("res://audio/music/FF_safezone.ogg")
	var overwrite_37 = preload("res://mods-unpacked/CrazyMew37-KevinMacLeodSoundpack/music/Who Likes to Party.mp3")
	overwrite_37.take_over_path("res://audio/music/LB_juryBG.ogg")
