extends Node

func _init():
	var overwrite_0 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/main_theme.ogg")
	overwrite_0.take_over_path("res://audio/music/main_theme.ogg")
	var overwrite_1 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/action_boss.ogg")
	overwrite_1.take_over_path("res://audio/music/action_boss.ogg")
	var overwrite_2 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/action_cash.ogg")
	overwrite_2.take_over_path("res://audio/music/action_cash.ogg")
	var overwrite_3 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/action_law.ogg")
	overwrite_3.take_over_path("res://audio/music/action_law.ogg")
	var overwrite_4 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/action_sell.ogg")
	overwrite_4.take_over_path("res://audio/music/action_sell.ogg")
	var overwrite_5 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/beta_installer.ogg")
	overwrite_5.take_over_path("res://audio/music/beta_installer.ogg")
	var overwrite_6 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/BossBot_CEO_v1.ogg")
	overwrite_6.take_over_path("res://audio/music/BossBot_CEO_v1.ogg")
	var overwrite_7 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/Bossbot_Entry_v2.ogg")
	overwrite_7.take_over_path("res://audio/music/Bossbot_Entry_v2.ogg")
	var overwrite_8 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/Bossbot_Factory_v1.ogg")
	overwrite_8.take_over_path("res://audio/music/Bossbot_Factory_v1.ogg")
	var overwrite_9 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/Bossbot_Factory_v2.ogg")
	overwrite_9.take_over_path("res://audio/music/Bossbot_Factory_v2.ogg")
	var overwrite_10 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/Bossbot_Factory_v3.ogg")
	overwrite_10.take_over_path("res://audio/music/Bossbot_Factory_v3.ogg")
	var overwrite_11 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/CHQ_FACT_bg.ogg")
	overwrite_11.take_over_path("res://audio/music/CHQ_FACT_bg.ogg")
	var overwrite_12 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/climb_boss.ogg")
	overwrite_12.take_over_path("res://audio/music/climb_boss.ogg")
	var overwrite_13 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/clown_boss.ogg")
	overwrite_13.take_over_path("res://audio/music/clown_boss.ogg")
	var overwrite_14 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/DA_Office.ogg")
	overwrite_14.take_over_path("res://audio/music/DA_Office.ogg")
	var overwrite_15 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/encntr_general_bg.ogg")
	overwrite_15.take_over_path("res://audio/music/encntr_general_bg.ogg")
	var overwrite_16 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/encntr_general_bg_indoor.ogg")
	overwrite_16.take_over_path("res://audio/music/encntr_general_bg_indoor.ogg")
	var overwrite_17 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/encntr_hall_of_fame.ogg")
	overwrite_17.take_over_path("res://audio/music/encntr_hall_of_fame.ogg")
	var overwrite_18 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/encntr_skull_master.ogg")
	overwrite_18.take_over_path("res://audio/music/encntr_skull_master.ogg")
	var overwrite_19 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/encntr_suit_winning.ogg")
	overwrite_19.take_over_path("res://audio/music/encntr_suit_winning.ogg")
	var overwrite_20 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/encntr_toon_winning_indoor.ogg")
	overwrite_20.take_over_path("res://audio/music/encntr_toon_winning_indoor.ogg")
	var overwrite_21 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/estate.ogg")
	overwrite_21.take_over_path("res://audio/music/estate.ogg")
	var overwrite_22 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/FF_safezone.ogg")
	overwrite_22.take_over_path("res://audio/music/FF_safezone.ogg")
	var overwrite_23 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/installer.ogg")
	overwrite_23.take_over_path("res://audio/music/installer.ogg")
	var overwrite_24 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/LB_juryBG.ogg")
	overwrite_24.take_over_path("res://audio/music/LB_juryBG.ogg")
	var overwrite_25 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/MG_Pairing.ogg")
	overwrite_25.take_over_path("res://audio/music/MG_Pairing.ogg")
	var overwrite_26 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/radio_tune2.ogg")
	overwrite_26.take_over_path("res://audio/music/radio_tune2.ogg")
	var overwrite_27 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/seize_the_means.ogg")
	overwrite_27.take_over_path("res://audio/music/seize_the_means.ogg")
	var overwrite_28 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/shopping.ogg")
	overwrite_28.take_over_path("res://audio/music/shopping.ogg")
	var overwrite_29 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/tc_streets.ogg")
	overwrite_29.take_over_path("res://audio/music/tc_streets.ogg")
	var overwrite_30 = preload("res://mods-unpacked/CrazyMew37-NightlifeSoundpack/audio/music/tt_elevator.ogg")
	overwrite_30.take_over_path("res://audio/music/tt_elevator.ogg")
